base_url = "https://yoloinfinity55.github.io/zola-mac/"
title = "Zola-mac"
description = "A blog about building beautiful static sites with Zola on macOS."
compile_sass = false
build_search_index = false
ignored_content = ["blog/archive/*.md"]

taxonomies = [
    { name = "tags", feed = true }
]

[markdown]
highlight_code = true
